/*-
 * Copyright 2009, 2010 Bjoern Koenig
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#if !defined(__API_H__)
#define __API_H__

#include "clara.h"

enum cl_function_t {

	/* 4.1 */
	CL_GETPLATFORMIDS = 0,
	CL_GETPLATFORMINFO,

	/* 4.2 */
	CL_GETDEVICEIDS,
	CL_GETDEVICEINFO,

	/* 4.3 */
	CL_CREATECONTEXT,
	CL_CREATECONTEXTFROMTYPE,
	CL_RETAINCONTEXT,
	CL_RELEASECONTEXT,
	CL_GETCONTEXTINFO,

	/* 5.1 */
	CL_CREATECOMMANDQUEUE,
	CL_RETAINCOMMANDQUEUE,
	CL_RELEASECOMMANDQUEUE,
	CL_GETCOMMANDQUEUEINFO,
	CL_SETCOMMANDQUEUEPROPERTY,

	/* 5.2.1 */
	CL_CREATEBUFFER,

	/* 5.2.2 */
	CL_ENQUEUEREADBUFFER,
	CL_ENQUEUEWRITEBUFFER,
	CL_ENQUEUECOPYBUFFER,

	/* 5.2.3 */
	CL_RETAINMEMOBJECT,
	CL_RELEASEMEMOBJECT,

	/* 5.2.4 */
	CL_CREATEIMAGE2D,
	CL_CREATEIMAGE3D,

	/* 5.2.5 */
	CL_GETSUPPORTEDIMAGEFORMATS,

	/* 5.2.6 */
	CL_ENQUEUEREADIMAGE,
	CL_ENQUEUEWRITEIMAGE,
	CL_ENQUEUECOPYIMAGE,

	/* 5.2.7 */
	CL_ENQUEUECOPYIMAGETOBUFFER,
	CL_ENQUEUECOPYBUFFERTOIMAGE,

	/* 5.2.8 */
	CL_ENQUEUEMAPBUFFER,
	CL_ENQUEUEMAPIMAGE,
	CL_ENQUEUEUNMAPMEMOBJECT,

	/* 5.2.9 */
	CL_GETMEMOBJECTINFO,
	CL_GETIMAGEINFO,

	/* 5.3 */
	CL_CREATESAMPLER,
	CL_RETAINSAMPLER,
	CL_RELEASESAMPLER,
	CL_GETSAMPLERINFO,

	/* 5.4.1 */
	CL_CREATEPROGRAMWITHSOURCE,
	CL_CREATEPROGRAMWITHBINARY,
	CL_RETAINPROGRAM,
	CL_RELEASEPROGRAM,

	/* 5.4.2 */
	CL_BUILDPROGRAM,

	/* 5.4.4 */
	CL_UNLOADCOMPILER,

	/* 5.4.5 */
	CL_GETPROGRAMINFO,
	CL_GETPROGRAMBUILDINFO,

	/* 5.5.1 */
	CL_CREATEKERNEL,
	CL_CREATEKERNELSINPROGRAM,
	CL_RETAINKERNEL,
	CL_RELEASEKERNEL,

	/* 5.5.2 */
	CL_SETKERNELARG,

	/* 5.5.3 */
	CL_GETKERNELINFO,
	CL_GETKERNELWORKGROUPINFO,

	/* 5.6 */
	CL_ENQUEUENDRANGEKERNEL,
	CL_ENQUEUETASK,
	CL_ENQUEUENATIVEKERNEL,

	/* 5.7 */
	CL_WAITFOREVENTS,
	CL_GETEVENTINFO,
	CL_RETAINEVENT,
	CL_RELEASEEVENT,

	/* 5.8 */
	CL_ENQUEUEMARKER,
	CL_ENQUEUEWAITFOREVENTS,
	CL_ENQUEUEBARRIER,

	/* 5.9 */
	CL_GETEVENTPROFILINGINFO,

	/* 5.10 */
	CL_FLUSH,
	CL_FINISH

}; /* enum cl_function_t */

struct cl_function_info {

	enum cl_function_t id;
	const char *name;
	size_t argc;

};

extern const struct cl_function_info clfuninfo[];

const struct cl_function_info *opencl_get_clfuninfo(enum cl_function_t id);

#endif /* __API_H__ */
